drop table if exists ninja CASCADE;
create table ninja (id integer generated by default as identity, age integer, village varchar(255), name varchar(255) not null, jutsu varchar(255), primary key (id));
